# site settings

title: 0xded093
description: Security Researcher
taglong: Security Researcher
tagshort:
url: https://0xded093.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/0xded093/0xded093.github.io

# author settings

author:
  name: Andrea De Dominicis
  email: andrea.dedominicis@me.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: 0xded093
  twitter: 0xded093

# build settings
plugins:
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

autopages:
  enabled: false
